//! Integration tests asserting the committed `tests/vectors.json` — the one shared
//! artifact both `crates/herdr-relay-proto` and `app/test/models/vectors_test.dart`
//! read directly — round-trips through `Frame` and `Message`, and is provably the
//! same data as the in-crate `test_vectors::message_vectors` function
//! (`docs/40-repo-tooling.md` R-40-031,
//! `docs/90-implementation-plan.md` §5.2 Phase 5 "Done when").
//!
//! `vectors.json` is not hand-maintained. It is generated by actually serializing
//! real `Frame` values with `serde_json`, via the `#[ignore]`d
//! [`regenerate_vectors_json`] test below, so its content is provably what this
//! crate's own types produce, not a value copied by hand into two places. Run it and
//! commit the result after changing a vector in `src/test_vectors.rs`:
//!
//! ```text
//! cargo test -p herdr-relay-proto --test vectors -- --ignored regenerate_vectors_json
//! ```

use std::collections::BTreeMap;

use herdr_relay_proto::frame::Frame;
use herdr_relay_proto::handle::{Handle, PairingUri};
use herdr_relay_proto::test_vectors::{
    EXAMPLE_HANDLE, EXAMPLE_PAIRING_URI, EXAMPLE_PHRASE, message_vectors,
};

/// R-11-240: the uncorrelated request uses the exact pane_id payload.
#[test]
fn mark_seen_round_trips_with_exact_payload() {
    use herdr_relay_proto::messages::{MarkSeen, Message};
    let message = Message::MarkSeen(MarkSeen {
        pane_id: "w28:p1R".to_owned(),
    });
    let value = serde_json::to_value(&message).unwrap();
    assert_eq!(
        value,
        serde_json::json!({"type":"mark_seen","payload":{"pane_id":"w28:p1R"}})
    );
    assert_eq!(message.type_name(), "mark_seen");
    assert_eq!(serde_json::from_value::<Message>(value).unwrap(), message);
    let frame = Frame::wrap(1, None, &message).unwrap();
    assert!(frame.corr.is_none());
    assert_eq!(frame.message().unwrap(), message);
}

fn vectors_json_path() -> String {
    concat!(env!("CARGO_MANIFEST_DIR"), "/tests/vectors.json").to_owned()
}

/// Builds the shared vector document from the in-crate constants, by wrapping each
/// real, typed [`herdr_relay_proto::messages::Message`] instance in a [`Frame`] via
/// [`Frame::wrap`] — the same call the Host and the Device use to build an outgoing
/// frame — and re-serializing it with `serde_json`. This exercises this crate's actual
/// `#[derive(Serialize)]` implementations, so the committed file reflects their real
/// field-presence behaviour (explicit `null` vs. an omitted key), not a hand-typed
/// JSON shape.
fn build_vectors_document() -> serde_json::Value {
    let mut messages = BTreeMap::new();
    for (type_name, seq, corr, message) in message_vectors() {
        let frame = Frame::wrap(seq, corr, &message)
            .unwrap_or_else(|error| panic!("vector {type_name} does not wrap: {error}"));
        let value = serde_json::to_value(&frame)
            .unwrap_or_else(|error| panic!("vector {type_name} does not re-serialize: {error}"));
        messages.insert(type_name.to_owned(), value);
    }
    serde_json::json!({
        "example_handle": EXAMPLE_HANDLE,
        "example_phrase": EXAMPLE_PHRASE,
        "example_pairing_uri": EXAMPLE_PAIRING_URI,
        "messages": messages,
    })
}

/// Regenerates `tests/vectors.json` from `src/test_vectors.rs`. Not run by default;
/// run explicitly and commit the result after changing a vector.
#[ignore = "golden-file generator: run explicitly, then commit tests/vectors.json"]
#[test]
fn regenerate_vectors_json() {
    let document = build_vectors_document();
    let pretty = serde_json::to_string_pretty(&document).expect("document always serializes");
    std::fs::write(vectors_json_path(), pretty + "\n").expect("tests/vectors.json is writable");
}

/// The committed `tests/vectors.json` must be exactly what
/// [`build_vectors_document`] produces right now. A drift here means someone edited
/// `src/test_vectors.rs` (or hand-edited the JSON) without regenerating the file, and
/// the Rust and Dart codecs can no longer be proven to agree.
#[test]
fn vectors_json_matches_the_in_crate_constants() {
    let on_disk = std::fs::read_to_string(vectors_json_path())
        .expect("tests/vectors.json must be committed; run regenerate_vectors_json");
    let on_disk: serde_json::Value =
        serde_json::from_str(&on_disk).expect("tests/vectors.json must be valid JSON");
    let expected = build_vectors_document();
    assert_eq!(
        on_disk, expected,
        "tests/vectors.json is stale — run `cargo test -p herdr-relay-proto --test vectors -- \
         --ignored regenerate_vectors_json` and commit the result"
    );
}

/// Every message vector in the committed JSON file decodes as its declared type and
/// round-trips through `Frame::wrap` byte for byte.
#[test]
fn vectors_json_messages_round_trip_through_frame_and_message() {
    let on_disk = std::fs::read_to_string(vectors_json_path())
        .expect("tests/vectors.json must be committed; run regenerate_vectors_json");
    let document: serde_json::Value =
        serde_json::from_str(&on_disk).expect("tests/vectors.json must be valid JSON");
    let messages = document["messages"]
        .as_object()
        .expect("vectors.json must have a messages object");
    assert!(
        !messages.is_empty(),
        "vectors.json must hold at least one message"
    );

    for (type_name, frame_json) in messages {
        let bytes = serde_json::to_vec(frame_json).expect("re-encodes to bytes");
        let frame = Frame::from_json_bytes(&bytes)
            .unwrap_or_else(|error| panic!("vector {type_name} is not a valid frame: {error}"));
        assert_eq!(frame.message_type, *type_name);

        let message = frame
            .message()
            .unwrap_or_else(|error| panic!("vector {type_name} does not decode: {error}"));
        assert_eq!(message.type_name(), type_name.as_str());

        let rebuilt = Frame::wrap(frame.seq, frame.corr.clone(), &message)
            .unwrap_or_else(|error| panic!("vector {type_name} does not re-wrap: {error}"));
        let re_decoded = rebuilt
            .message()
            .unwrap_or_else(|error| panic!("vector {type_name} re-wrap does not decode: {error}"));
        assert_eq!(
            re_decoded, message,
            "vector {type_name} must round-trip through Frame::wrap"
        );
    }
}

#[test]
fn vectors_json_covers_every_documented_message_type() {
    // docs/11-relay-protocol.md §4's 26-row table (including send_input_ack as 12a).
    const EXPECTED: &[&str] = &[
        "host_info",
        "device_info",
        "tree_request",
        "tree_snapshot",
        "tree_update",
        "watch_pane",
        "watch_ack",
        "unwatch_pane",
        "pane_frame",
        "scroll_request",
        "scroll_response",
        "send_input",
        "send_input_ack",
        "agent_status",
        "agent_prompt",
        "agent_prompt_ack",
        "host_action",
        "host_action_ack",
        "device_list_request",
        "device_list",
        "revoke_device",
        "revoke_result",
        "error",
        "disconnect",
        "action_list_request",
        "action_list",
    ];
    let on_disk = std::fs::read_to_string(vectors_json_path())
        .expect("tests/vectors.json must be committed; run regenerate_vectors_json");
    let document: serde_json::Value =
        serde_json::from_str(&on_disk).expect("tests/vectors.json must be valid JSON");
    let messages = document["messages"]
        .as_object()
        .expect("vectors.json must have a messages object");
    for expected in EXPECTED {
        assert!(
            messages.contains_key(*expected),
            "message type {expected} has no vector in tests/vectors.json"
        );
    }
    assert_eq!(
        messages.len(),
        EXPECTED.len(),
        "vector count must match the table"
    );
}

#[test]
fn vectors_json_example_handle_and_phrase_round_trip_through_the_pairing_uri() {
    let on_disk = std::fs::read_to_string(vectors_json_path())
        .expect("tests/vectors.json must be committed; run regenerate_vectors_json");
    let document: serde_json::Value =
        serde_json::from_str(&on_disk).expect("tests/vectors.json must be valid JSON");
    let example_handle = document["example_handle"]
        .as_str()
        .expect("example_handle must be a string");
    let example_phrase = document["example_phrase"]
        .as_str()
        .expect("example_phrase must be a string");
    let example_pairing_uri = document["example_pairing_uri"]
        .as_str()
        .expect("example_pairing_uri must be a string");

    let handle: Handle = example_handle
        .parse()
        .expect("worked-example handle is valid");
    assert_eq!(handle.encode(), example_handle);

    let parsed = PairingUri::parse(example_pairing_uri).expect("worked-example URI is valid");
    assert_eq!(parsed.relay_origin, "https://relay.example.com");
    assert_eq!(parsed.handle, handle);
    assert_eq!(parsed.phrase, example_phrase);
    assert_eq!(parsed.build(), example_pairing_uri);
}
