/// Loads the single vector file `crates/herdr-relay-proto/tests/vectors.json`
/// that both `crates/herdr-relay-proto/tests/vectors.rs` and this file read,
/// and proves the Dart model layer (`app/lib/models/frame.dart`,
/// `app/lib/models/message.dart`) decodes it byte for byte the same way the
/// Rust codec does (`docs/90-implementation-plan.md` §5.2 `WP-5-c`, Phase
/// 5's `Done when` line).
///
/// The file is machine-generated by serializing real Rust `Frame`/`Message`
/// values (not hand-typed), and a Rust-side test
/// (`vectors_json_matches_the_in_crate_constants`) fails the build if it
/// ever drifts from `crates/herdr-relay-proto/src/test_vectors.rs`. This
/// file has no hand-transcribed protocol literal: every assertion below
/// reads its expected value from the file itself.
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import 'package:herdr_mobile/models/frame.dart';
import 'package:herdr_mobile/models/message.dart';

/// Relative to the package root, which is `flutter test`'s working
/// directory (`app/`). `crates/` is `app/`'s sibling.
const String _vectorsPath = '../crates/herdr-relay-proto/tests/vectors.json';

/// The 26-row message table in `docs/11-relay-protocol.md` §4 (`12a` is
/// `send_input_ack`), also asserted on the Rust side in
/// `crates/herdr-relay-proto/tests/vectors.rs:49-76`.
const List<String> documentedMessageTypes = [
  'host_info',
  'device_info',
  'tree_request',
  'tree_snapshot',
  'tree_update',
  'watch_pane',
  'watch_ack',
  'unwatch_pane',
  'pane_frame',
  'scroll_request',
  'scroll_response',
  'send_input',
  'send_input_ack',
  'agent_status',
  'agent_prompt',
  'agent_prompt_ack',
  'host_action',
  'host_action_ack',
  'device_list_request',
  'device_list',
  'revoke_device',
  'revoke_result',
  'error',
  'disconnect',
  'action_list_request',
  'action_list',
  'ping',
  'pong',
];

void main() {
  late Map<String, dynamic> vectors;
  late Map<String, dynamic> messageVectors;

  setUpAll(() {
    final contents = File(_vectorsPath).readAsStringSync();
    vectors = jsonDecode(contents) as Map<String, dynamic>;
    messageVectors = vectors['messages'] as Map<String, dynamic>;
  });

  test('the shared vector file parses and holds a messages map', () {
    expect(vectors['example_handle'], isA<String>());
    expect(vectors['example_phrase'], isA<String>());
    expect(vectors['example_pairing_uri'], isA<String>());
    expect(messageVectors, isNotEmpty);
  });

  test('message vectors cover every documented message type exactly once', () {
    for (final expected in documentedMessageTypes) {
      expect(
        messageVectors.keys,
        contains(expected),
        reason: 'message type $expected has no test vector',
      );
    }
    expect(messageVectors.keys.length, equals(documentedMessageTypes.length));
  });

  test('every message vector round-trips through Frame and Message', () {
    for (final entry in messageVectors.entries) {
      final type = entry.key;
      final frameJson = entry.value as Map<String, dynamic>;

      // Frame.fromJson mirrors Frame::from_json_bytes
      // (crates/herdr-relay-proto/src/frame.rs:116-121): the whole
      // envelope, not just the payload.
      final frame = Frame.fromJson(frameJson);
      expect(frame.type, equals(type), reason: '$type: type must match');
      expect(frame.v, equals(1), reason: '$type: v must be 1');

      // messageFromTypeAndPayload mirrors Frame::message
      // (crates/herdr-relay-proto/src/frame.rs:83-92), reading the payload
      // key and switching on the type discriminator exactly as the
      // freezed union read R-20-010 requires.
      final message = messageFromTypeAndPayload(frame.type, frame.payload);
      expect(
        message.typeName,
        equals(type),
        reason: '$type: decoded message must report its own type',
      );

      // Re-wrapping the decoded message must reproduce the same payload
      // (crates/herdr-relay-proto/tests/vectors.rs:26-44,
      // "every_message_vector_round_trips_byte_for_byte_through_message").
      expect(
        message.payloadJson,
        equals(frame.payload),
        reason: '$type: payload must round-trip through the model layer',
      );

      // The full envelope must also round-trip through Frame itself.
      expect(
        Frame.fromJson(frame.toJson()).toJson(),
        equals(frame.toJson()),
        reason: '$type: Frame must round-trip through fromJson/toJson',
      );
    }
  });

  test('the example handle and phrase round-trip through the pairing URI', () {
    final handle = vectors['example_handle'] as String;
    final phrase = vectors['example_phrase'] as String;
    final pairingUri = vectors['example_pairing_uri'] as String;

    // R-11-112: 22 unpadded base64url characters.
    expect(handle.length, equals(22));
    expect(RegExp(r'^[A-Za-z0-9_-]{22}$').hasMatch(handle), isTrue);

    // R-13-019: six lowercase hyphenated words.
    final words = phrase.split('-');
    expect(words.length, equals(6));
    for (final word in words) {
      expect(RegExp(r'^[a-z]+$').hasMatch(word), isTrue);
    }

    final uri = Uri.parse(pairingUri);
    expect(uri.scheme, equals('herdr-remote'));
    expect(uri.host, equals('pair'));

    final query = uri.queryParameters;
    expect(query['v'], equals('1'));
    expect(query['h'], equals(handle));
    expect(query['p'], equals(phrase));
  });
}
